name: variable in gha

on:
  push:
    branches:
      - main
env:
  check: checkout@v3
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      run:  "$check"
     
    