name: variable in gha

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      name: run one line
      run:  echo "vaibhav"
  
      
     
     